export default [
  {
    files: ['core/sqlite3.js'],
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['scripts/templates/script.js', 'ui/**/*.js', 'core/scrubber.test.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        performance: 'readonly',
        customElements: 'readonly',
        HTMLElement: 'readonly',
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        Blob: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        WebAssembly: 'readonly',
        Worker: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
      },
    },
  },
  {
    files: ['core/sync.js', 'core/voice.js'],
    languageOptions: {
      globals: {
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        window: 'readonly',
      },
    },
  },
  {
    files: ['core/**/*.js', 'test-suite.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __filename: 'readonly',
        __dirname: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        globalThis: 'readonly',
        crypto: 'readonly',
        fetch: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        WebSocket: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly',
        DataView: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        Int8Array: 'readonly',
        Int16Array: 'readonly',
        Int32Array: 'readonly',
        Uint8Array: 'readonly',
        Uint16Array: 'readonly',
        Uint32Array: 'readonly',
        Uint8ClampedArray: 'readonly',
        BigInt: 'readonly',
        BigInt64Array: 'readonly',
        BigUint64Array: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Error: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        Reflect: 'readonly',
        Proxy: 'readonly',
        Intl: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        eval: 'readonly',
        escape: 'readonly',
        unescape: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        parseFloat: 'readonly',
        parseInt: 'readonly',
        decodeURI: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURI: 'readonly',
        encodeURIComponent: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        Blob: 'readonly',
        DOMParser: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        BroadcastChannel: 'readonly',
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        CryptoKey: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-undef': 'error',
    },
  },
  {
    ignores: ['node_modules/', 'docs-site/', '.wrangler/', 'relay.sqlite', 'core/sqlite3.js'],
  },
];